### ISSUE TITLE
Running black screen

### ISSUE THREAD

**Issue by huangshh310** [jxqu3/aiui#1]
Running black screen

**Comment by jxqu3** [comment]
I'm sorry, can you elaborate?

**Comment by hillar** [comment]
> https://aiui-delta.vercel.app/
```
index-D7z79MRL.js:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at ys (index-D7z79MRL.js:14:20172)
    at se (index-D7z79MRL.js:4:4814)
    at new Cs (index-D7z79MRL.js:14:20509)
    at Ks (index-D7z79MRL.js:16:9321)
    at s (index-D7z79MRL.js:4:3197)
    at index-D7z79MRL.js:4:3472
    
    ```

**Comment by PetrSnobelt** [comment]
IIRC it happen on this 
https://github.com/jxqu3/aiui/blob/master/src/lib/ModelDropdown.svelte#L13
if for example oolama is not running then modelList is empty.

**Comment by jxqu3** [comment]
Oh, yeah, you need to have ollama started before opening the site

**Comment by jxqu3** [comment]
Alright, fixed in latest commit, let me know if it still happens!
